const COMMANDS: &[&str] = &[
	"init",
	"reload",
	"download",
	"get_ypk",
	"load_ypk",
	"unload_ypk",
	"chk_version",
	"get_srv",
	"get_pic",
	"get_sound",
	"get_textures",
	"get_cards",
	"get_system",
	"get_hash",
	"get_server",
	"get_strings",
	"get_lflist",
	"get_info",
	"get_room",
	"get_script",
	"get_deck",
	"get_time",
	"get_version",
	"set_system",
	"set_textures",
	"write_deck",
	"rename_deck",
	"del_deck",
	"write_log",
	"del_ypk",
	"exists_ypk",
	"ygoserver_start",
	"ygoserver_stop",
	"windbot_start",
	"windbot_stop",
	"windbot_list",
	"replay_read",
	"replay_save",
	"replay_list",
	"replay_rename",
	"replay_del",
	"js_load",
	"js_unload",
	"js_call",
	"plugin_read",
	"plugin_write",
];

fn main () {
	generate_default_permissions(COMMANDS);
	tauri_plugin::Builder::new(COMMANDS).build();
}

fn generate_default_permissions (commands: &[&str]) {
	let mut permissions = String::from(
		"\"$schema\" = \"schemas/schema.json\"\n\n\
		# Automatically generated by src/build.rs - DO NOT EDIT!\n\n\
		[default]\n\
		description = \"Default permissions for the ygopro3 plugin.\"\n\
		permissions = [\n",
	);

	for command in commands {
		let permission = command.replace('_', "-");
		permissions.push_str(&format!("\t\"allow-{permission}\",\n"));
	}

	permissions.push_str("]\n");

	let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set");
	let permissions_dir = std::path::Path::new(&manifest_dir).join("permissions");
	let permissions_file = permissions_dir.join("default.toml");
	std::fs::create_dir_all(&permissions_dir).expect("failed to create permissions directory");
	if std::fs::read_to_string(&permissions_file).ok().as_deref() != Some(permissions.as_str()) {
		std::fs::write(permissions_file, permissions).expect("failed to write permissions/default.toml");
	}
}
