[ot]
0x1 = "ot/ot_ocg.webp"
0x2 = "ot/ot_tcg.webp"
0x3 = "ot/ot_ocgtcg.webp"
0x4 = "ot/ot_custom.webp"
0x8 = "ot/ot_sc.webp"

[attribute]
0x1 = "attribute/attr_earth.webp"
0x2 = "attribute/attr_water.webp"
0x4 = "attribute/attr_fire.webp"
0x8 = "attribute/attr_wind.webp"
0x10 = "attribute/attr_light.webp"
0x20 = "attribute/attr_dark.webp"
0x40 = "attribute/attr_divine.webp"

[link]
0x40 = ["arrow/arrow-1-off.webp", "arrow/arrow-1-on.webp"]
0x80 = ["arrow/arrow-2-off.webp", "arrow/arrow-2-on.webp"]
0x100 = ["arrow/arrow-3-off.webp", "arrow/arrow-3-on.webp"]
0x8 = ["arrow/arrow-4-off.webp", "arrow/arrow-4-on.webp"]
0x20 = ["arrow/arrow-5-off.webp", "arrow/arrow-5-on.webp"]
0x1 = ["arrow/arrow-6-off.webp", "arrow/arrow-6-on.webp"]
0x2 = ["arrow/arrow-7-off.webp", "arrow/arrow-7-on.webp"]
0x4 = ["arrow/arrow-8-off.webp", "arrow/arrow-8-on.webp"]

[category]
0x1 = "category/category_destroySpellTrap.webp"
0x2 = "category/category_destroyMonster.webp"
0x4 = "category/category_banish.webp"
0x8 = "category/category_sendToGraveyard.webp"
0x10 = "category/category_returnToHand.webp"
0x20 = "category/category_returnToDeck.webp"
0x40 = "category/category_destroyHand.webp"
0x80 = "category/category_destroyDeck.webp"
0x100 = "category/category_draw.webp"
0x200 = "category/category_search.webp"
0x400 = "category/category_recovery.webp"
0x800 = "category/category_position.webp"
0x1000 = "category/category_control.webp"
0x2000 = "category/category_changeAtkDef.webp"
0x4000 = "category/category_piercing.webp"
0x8000 = "category/category_repeatAttack.webp"
0x10000 = "category/category_limitAttack.webp"
0x20000 = "category/category_directAttack.webp"
0x40000 = "category/category_specialSummon.webp"
0x80000 = "category/category_token.webp"
0x100000 = "category/category_raceRelated.webp"
0x200000 = "category/category_attributeRelated.webp"
0x400000 = "category/category_damageLP.webp"
0x800000 = "category/category_recoverLP.webp"
0x1000000 = "category/category_undestroyable.webp"
0x2000000 = "category/category_ineffective.webp"
0x4000000 = "category/category_counter.webp"
0x8000000 = "category/category_gamble.webp"
0x10000000 = "category/category_fusionRelated.webp"
0x20000000 = "category/category_synchroRelated.webp"
0x40000000 = "category/category_xyzRelated.webp"
0x80000000 = "category/category_negateEffect.webp"

[race]
0x1 = "race/race_warrior.webp"
0x2 = "race/race_spell-caster.webp"
0x4 = "race/race_fairy.webp"
0x8 = "race/race_fiend.webp"
0x10 = "race/race_zombie.webp"
0x20 = "race/race_machine.webp"
0x40 = "race/race_aqua.webp"
0x80 = "race/race_pyro.webp"
0x100 = "race/race_rock.webp"
0x200 = "race/race_wind-beast.webp"
0x400 = "race/race_plant.webp"
0x800 = "race/race_insect.webp"
0x1000 = "race/race_thunder.webp"
0x2000 = "race/race_dragon.webp"
0x4000 = "race/race_beast.webp"
0x8000 = "race/race_beast-warrior.webp"
0x10000 = "race/race_dinosaur.webp"
0x20000 = "race/race_fish.webp"
0x40000 = "race/race_sea-serpent.webp"
0x80000 = "race/race_reptile.webp"
0x100000 = "race/race_psycho.webp"
0x200000 = "race/race_divine-beast.webp"
0x400000 = "race/race_create-god.webp"
0x800000 = "race/race_wyrm.webp"
0x1000000 = "race/race_cyberse.webp"
0x2000000 = "race/race_illusion.webp"

[types]
0x1 = "type/cardType_monster.webp"
0x10 = "type/type_normal.webp"
0x12 = "type/spellTrapType_normal.webp"
0x20 = "type/type_effect.webp"
0x1000 = "type/type_tuner.webp"
0x800 = "type/type_dual.webp"
0x200000 = "type/type_flip.webp"
0x400 = "type/type_union.webp"
0x200 = "type/type_spirit.webp"
0x400000 = "type/type_toon.webp"
0x40 = "type/type_fusion.webp"
0x2000 = "type/type_synchro.webp"
0x800000 = "type/type_xyz.webp"
0x1000000 = "type/type_pendulum.webp"
0x80 = "type/type_ritual.webp"
0x81 = "type/type_ritual.webp"
0x82 = "type/spellTrapType_ritual.webp"
0x2 = "type/cardType_spell.webp"
0x4 = "type/cardType_trap.webp"
0x10000 = "type/spellTrapType_quickplay.webp"
0x20000 = "type/spellTrapType_continuous.webp"
0x40000 = "type/spellTrapType_equip.webp"
0x80000 = "type/spellTrapType_field.webp"
0x100000 = "type/spellTrapType_counter.webp"
0x4000000 = "type/type_link.webp"
0x2000000 = "type/type_specialSummon.webp"
0x4000 = "type/type_token.webp"

[btn]
"ACTIVATE" = ["btn/btn_activate.webp", "btn/btn_hover_activate.webp"]
"SCALE" = ["btn/btn_scale.webp", "btn/btn_hover_scale.webp"]
"ATTACK" = ["btn/btn_attack.webp", "btn/btn_hover_attack.webp"]
"SUMMON" = ["btn/btn_summon.webp", "btn/btn_hover_summon.webp"]
"SPSUMMON" = ["btn/btn_spsummon.webp", "btn/btn_hover_spsummon.webp"]
"PSUMMON" = ["btn/btn_psummon.webp", "btn/btn_hover_psummon.webp"]
"FLIP" = ["btn/btn_flip.webp", "btn/btn_hover_flip.webp"]
"MSET" = ["btn/btn_mset.webp", "btn/btn_hover_mset.webp"]
"SSET" = ["btn/btn_sset.webp", "btn/btn_hover_sset.webp"]
"POS_ATTACK" = ["btn/btn_pos_attack.webp", "btn/btn_hover_pos_attack.webp"]
"POS_DEFENCE" = ["btn/btn_pos_defence.webp", "btn/btn_hover_pos_defence.webp"]

[info]
"LEVEL" = "info/info_level.webp"
"LINK" = "info/info_link.webp"
"OVERLAY" = "info/info_overlay.webp"
"RANK" = "info/info_rank.webp"
"SCALE" = "info/info_scale.webp"
"STAR_RANK_LINK" = "info/info_star_rank_link.webp"
"TUNER" = "info/info_tuner.webp"

[counter]
0x0 = "counter/counter_0.webp"
0x1 = "counter/counter_1.webp"
0x3 = "counter/counter_3.webp"
0x4 = "counter/counter_4.webp"
0x5 = "counter/counter_5.webp"
0x6 = "counter/counter_6.webp"
0x8 = "counter/counter_8.webp"
0xa = "counter/counter_a.webp"
0xc = "counter/counter_c.webp"
0xd = "counter/counter_d.webp"
0xf = "counter/counter_f.webp"
0x10 = "counter/counter_10.webp"
0x11 = "counter/counter_11.webp"
0x12 = "counter/counter_12.webp"
0x13 = "counter/counter_13.webp"
0x16 = "counter/counter_16.webp"
0x17 = "counter/counter_17.webp"
0x18 = "counter/counter_18.webp"
0x1a = "counter/counter_1a.webp"
0x1b = "counter/counter_1b.webp"
0x1c = "counter/counter_1c.webp"
0x1d = "counter/counter_1d.webp"
0x1e = "counter/counter_1e.webp"
0x20 = "counter/counter_20.webp"
0x22 = "counter/counter_22.webp"
0x23 = "counter/counter_23.webp"
0x25 = "counter/counter_25.webp"
0x2b = "counter/counter_2b.webp"
0x2c = "counter/counter_2c.webp"
0x2e = "counter/counter_2e.webp"
0x2f = "counter/counter_2f.webp"
0x30 = "counter/counter_30.webp"
0x31 = "counter/counter_31.webp"
0x32 = "counter/counter_32.webp"
0x33 = "counter/counter_33.webp"
0x35 = "counter/counter_35.webp"
0x36 = "counter/counter_36.webp"
0x37 = "counter/counter_37.webp"
0x43 = "counter/counter_43.webp"
0x4a = "counter/counter_4a.webp"
0x4b = "counter/counter_4b.webp"
0x4c = "counter/counter_4c.webp"
0x56 = "counter/counter_56.webp"
0x57 = "counter/counter_57.webp"
0x59 = "counter/counter_59.webp"
0x5e = "counter/counter_5e.webp"
0x5f = "counter/counter_5f.webp"
0x64 = "counter/counter_64.webp"
0x6a = "counter/counter_6a.webp"
0x1002 = "counter/counter_1002.webp"
0x1009 = "counter/counter_1009.webp"
0x100e = "counter/counter_100e.webp"
0x1015 = "counter/counter_1015.webp"
0x1019 = "counter/counter_1019.webp"
0x1021 = "counter/counter_1021.webp"
0x1024 = "counter/counter_1024.webp"
0x102a = "counter/counter_102a.webp"
0x1038 = "counter/counter_1038.webp"
0x1039 = "counter/counter_1039.webp"
0x1041 = "counter/counter_1041.webp"
0x1045 = "counter/counter_1045.webp"
0x1049 = "counter/counter_1049.webp"
0x104d = "counter/counter_104d.webp"
0x104f = "counter/counter_104f.webp"
0x105c = "counter/counter_105c.webp"
0x1063 = "counter/counter_1063.webp"
0x1065 = "counter/counter_1065.webp"
0x1072 = "counter/counter_1072.webp"

[avatar]
"AVATAR" = [
    "avatar/avatar_0.webp",
    "avatar/avatar_1.webp",
    "avatar/avatar_2.webp",
    "avatar/avatar_3.webp",
    "avatar/avatar_4.webp",
    "avatar/avatar_5.webp",
    "avatar/avatar_6.webp"
]

[other]
"COVER" = "other/cover.webp"
"UNKNOWN" = "other/unknown.webp"
"BACKI" = ""
"BACKII" = ""
"S" = "other/s.webp"
"R" = "other/r.webp"
"P" = "other/p.webp"

[sound]
"BACK_BGM" = "Night View.mp3"
"BATTLE_BGM" = "City of Night.mp3"
"SOUND_EFFECT_ACTIVATE" = "activate.ogg"
"SOUND_EFFECT_ADDCOUNTER" = "addcounter.ogg"
"SOUND_EFFECT_ATTACK" = "attack.ogg"
"SOUND_EFFECT_CHATMESSAGE" = "chatmessage.ogg"
"SOUND_EFFECT_COINFLIP" = "coinflip.ogg"
"SOUND_EFFECT_DAMAGE" = "damage.ogg"
"SOUND_EFFECT_DESTROYED" = "destroyed.ogg"
"SOUND_EFFECT_DICEROLL" = "diceroll.ogg"
"SOUND_EFFECT_DRAW" = "draw.ogg"
"SOUND_EFFECT_EQUIP" = "equip.ogg"
"SOUND_EFFECT_EXPLODE" = "explode.ogg"
"SOUND_EFFECT_FLIP" = "flip.ogg"
"SOUND_EFFECT_GAINLP" = "gainlp.ogg"
"SOUND_EFFECT_NEXTTURN" = "nextturn.ogg"
"SOUND_EFFECT_PHASE" = "phase.ogg"
"SOUND_EFFECT_PLAYERENTER" = "playerenter.ogg"
"SOUND_EFFECT_REMOVECOUNTER" = "removecounter.ogg"
"SOUND_EFFECT_SET" = "set.ogg"
"SOUND_EFFECT_SHUFFLE" = "shuffle.ogg"
"SOUND_EFFECT_SPECIALSUMMON" = "specialsummon.ogg"
"SOUND_EFFECT_SUMMON" = "summon.ogg"

[recognizer]
"hash" = "card_data"