name: build YGOPro3

on:
  push:
    branches: [test]
    
jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tauri_target: aarch64
            apk_abi: arm64
            artifact_abi: arm64-v8a
          - tauri_target: armv7
            apk_abi: arm
            artifact_abi: armeabi-v7a
          - tauri_target: i686
            apk_abi: x86
            artifact_abi: x86
          - tauri_target: x86_64
            apk_abi: x86_64
            artifact_abi: x86_64
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK and NDK
      uses: android-actions/setup-android@v3
      with:
        accept-android-sdk-licenses: true

    - name: Set Android Environment
      run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        echo "NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH
        NDK_SYSROOT="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
        case "${{ matrix.tauri_target }}" in
          aarch64)
            BINDGEN_TARGET_INCLUDE="aarch64-linux-android"
            ;;
          armv7)
            BINDGEN_TARGET_INCLUDE="arm-linux-androideabi"
            ;;
          i686)
            BINDGEN_TARGET_INCLUDE="i686-linux-android"
            ;;
          x86_64)
            BINDGEN_TARGET_INCLUDE="x86_64-linux-android"
            ;;
        esac
        echo "BINDGEN_EXTRA_CLANG_ARGS=--sysroot=$NDK_SYSROOT -isystem $NDK_SYSROOT/usr/include -isystem $NDK_SYSROOT/usr/include/$BINDGEN_TARGET_INCLUDE" >> $GITHUB_ENV

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.95.0

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Download assets
      uses: robinraju/release-downloader@v1.10
      with:
        tag: assets-latest
        fileName: "assets.zip"
        out-file-path: "./src-tauri/"
        
    - name: Rename assets
      run: mv ./src-tauri/assets.zip ./src-tauri/assets

    - name: Write Tauri Config
      run: |
        npm run json:build android 2026.08.29

    - name: NPM Init
      run: |
        npm ci
    
    - name: Android Init
      run: |
        npm run tauri:android:init:sh

    - name: Install wget and unzip
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip

    - name: Download so
      run: |
        cd kotlin/jniLibs
        mkdir x86
        mkdir x86_64
        mkdir arm64-v8a
        mkdir armeabi-v7a

        cd x86_64
        wget https://github.com/jwyxym/windbot/releases/download/release-latest/windbot-android-x86_64.zip
        unzip windbot-android-x86_64.zip
        rm -r *.zip

        cd ../arm64-v8a
        wget https://github.com/jwyxym/windbot/releases/download/release-latest/windbot-android-arm64-v8a.zip
        unzip windbot-android-arm64-v8a.zip
        rm -r *.zip

        cd ../armeabi-v7a
        wget https://github.com/jwyxym/windbot/releases/download/release-latest/windbot-android-armeabi-v7a.zip
        unzip windbot-android-armeabi-v7a.zip
        rm -r *.zip

    - name: Android build (${{ matrix.artifact_abi }})
      run: |
        npm run copy:sh
        npm run tauri:android:build -- --apk --target ${{ matrix.tauri_target }}

    - name: Git Config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Set SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Decode Keystore File
      run: |
        git clone ${{ secrets.KEYSTORE_REPO }} --depth 1 jks
        mv jks/ygopro3.jks ./YGOPro3.jks

    - name: Sign apk (${{ matrix.artifact_abi }})
      run: |
        mkdir build
        apksigner sign --ks ./YGOPro3.jks --ks-key-alias ${{ secrets.KEY_ALIAS }} --key-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --out ./build/YGOPro3-${{ matrix.artifact_abi }}.apk ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk

    - name: Upload (${{ matrix.artifact_abi }})
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-${{ matrix.artifact_abi }}.apk
        retention-days: 1
        path: ./build/YGOPro3-${{ matrix.artifact_abi }}.apk

  build-windows:
    name: build-windows-${{ matrix.target }}
    runs-on: ${{ matrix.run-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64
            run-on: windows-latest
          - target: aarch64
            run-on: windows-11-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.95.0

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Download assets
      uses: robinraju/release-downloader@v1.10
      with:
        tag: assets-latest
        fileName: "assets.zip"
        out-file-path: "./src-tauri/"
        
    - name: Rename assets
      run: move src-tauri\assets.zip src-tauri\assets

    - name: Install wget and unzip
      run: choco install wget unzip -y

    - name: Download Windbot
      if: matrix.target == 'aarch64'
      run: |
        cd src-tauri
        wget https://github.com/jwyxym/windbot/releases/download/release-latest/windbot-win-arm64.zip
        unzip windbot-win-arm64.zip

    - name: Download Windbot
      if: matrix.target == 'x86_64'
      run: |
        cd src-tauri
        wget https://github.com/jwyxym/windbot/releases/download/release-latest/windbot-win-x64.zip
        unzip windbot-win-x64.zip

    - name: Write Tauri Config
      shell: cmd
      run: |
        npm run json:build windows 2026.08.29

    - name: NPM Init
      run: |
        npm ci

    - name: Windows build
      run: |
        npm run tauri:build
    
    - name: Copy
      shell: cmd
      run: |
        set "found_msi="
        set "found_exe="
        mkdir build

        for %%f in (.\src-tauri\target\release\bundle\msi\*) do (
            if not defined found_msi (
                copy "%%f" ".\build\YGOPro3.msi"
                set "found_msi=1"
            )
        )

        for %%f in (.\src-tauri\target\release\bundle\nsis\*) do (
            if not defined found_exe (
                copy "%%f" ".\build\YGOPro3.exe"
                set "found_exe=1"
            )
        )

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-windows-${{ matrix.target }}.exe
        retention-days: 1
        path: .\build\YGOPro3.exe

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-windows-${{ matrix.target }}.msi
        retention-days: 1
        path: .\build\YGOPro3.msi

  build-macos:
    name: build-macos-${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64
          - target: aarch64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.95.0
        target: ${{ matrix.target }}-apple-darwin

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Download assets
      uses: robinraju/release-downloader@v1.10
      with:
        tag: assets-latest
        fileName: "assets.zip"
        out-file-path: "./src-tauri/"
        
    - name: Rename assets
      run: mv ./src-tauri/assets.zip ./src-tauri/assets

    - name: Download Windbot
      run: |
        cd src-tauri
        wget https://github.com/jwyxym/windbot/releases/download/release-latest/windbot-macos-universal.zip
        unzip windbot-macos-universal.zip

    - name: Write Tauri Config
      run: |
        npm run json:build macos 2026.08.29

    - name: NPM Init
      run: |
        npm ci

    - name: Macos build
      run: |
        npm run tauri:build

    - name: Zip .app
      run: |
        cd ./src-tauri/target/release/bundle/macos/
        zip -r YGOPro3.app.zip ygopro3.app

    - name: Copy
      run: |
        mkdir -p ./build
        DMG_FILES=(./src-tauri/target/release/bundle/dmg/*.dmg)
        cp "${DMG_FILES[0]}" ./build/YGOPro3.dmg

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-macos-${{ matrix.target }}.dmg
        retention-days: 1
        path: ./build/YGOPro3.dmg

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-macos-${{ matrix.target }}.app.zip
        retention-days: 1
        path: ./src-tauri/target/release/bundle/macos/YGOPro3.app.zip

  build-linux:
    name: build-linux-${{ matrix.target }}-${{ matrix.bundle }}
    runs-on: ${{ matrix.run-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64
            run-on: ubuntu-latest
            bundle: deb
            bundle_dir: deb
            extension: deb
          - target: aarch64
            run-on: ubuntu-24.04-arm
            bundle: deb
            bundle_dir: deb
            extension: deb
          - target: x86_64
            run-on: ubuntu-latest
            bundle: rpm
            bundle_dir: rpm
            extension: rpm
          - target: aarch64
            run-on: ubuntu-24.04-arm
            bundle: rpm
            bundle_dir: rpm
            extension: rpm
          - target: x86_64
            run-on: ubuntu-latest
            bundle: appimage
            bundle_dir: appimage
            extension: AppImage
          - target: aarch64
            run-on: ubuntu-24.04-arm
            bundle: appimage
            bundle_dir: appimage
            extension: AppImage
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.95.0

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Download assets
      uses: robinraju/release-downloader@v1.10
      with:
        tag: assets-latest
        fileName: "assets.zip"
        out-file-path: "./src-tauri/"

    - name: Rename assets
      run: mv ./src-tauri/assets.zip ./src-tauri/assets

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          librsvg2-dev \
          libglib2.0-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libatk1.0-dev \
          libgdk-pixbuf2.0-dev \
          build-essential \
          libssl-dev \
          libasound2-dev \
          pkg-config \
          libgtk-3-dev \
          xdg-utils

    - name: Download Windbot
      if: matrix.target == 'aarch64'
      run: |
        cd src-tauri
        wget https://github.com/jwyxym/windbot/releases/download/release-latest/windbot-linux-arm64.zip
        unzip windbot-linux-arm64.zip

    - name: Download Windbot
      if: matrix.target == 'x86_64'
      run: |
        cd src-tauri
        wget https://github.com/jwyxym/windbot/releases/download/release-latest/windbot-linux-x64.zip
        unzip windbot-linux-x64.zip

    - name: Write Tauri Config
      run: |
        npm run json:build linux 2026.08.29 ${{ matrix.bundle }}

    - name: NPM Init
      run: |
        npm ci

    - name: Build
      run: |
        npm run tauri:build

    - name: Copy
      run: |
        mkdir -p ./build
        cp ./src-tauri/target/release/bundle/${{ matrix.bundle_dir }}/*.${{ matrix.extension }} ./build/YGOPro3.${{ matrix.extension }}

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-linux-${{ matrix.target }}.${{ matrix.extension }}
        retention-days: 1
        path: ./build/YGOPro3.${{ matrix.extension }}
